name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 4: Build the Spring Boot app
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub using CLI
        uses: docker login -u nikshitakarkera -p ${{secrets.DOCKER_HUB_TOKEN}}

      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t nikshitakarkera/springbootdemo:latest .

      # Step 7: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push nikshitakarkera/springbootdemo:latest
